---
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
 
# Do NOT remove the RETAIL_DS prefix in the template description below!
Description: >
  RETAIL_DS: This template deploys the Retail Demo Store reference architecture and workshop notebooks. (uksb-1t80l2nq1)
 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Retail Demo Store Deployment Configuration"
        Parameters:
          - ResourceBucket
          - ResourceBucketRelativePath
          - CreateOpenSearchServiceLinkedRole
      - Label:
          default: "Source Deployment Approach"
        Parameters:
          - SourceDeploymentType
      - Label:
          default: "GitHub Repository"
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubToken
      - Label:
          default: "Auto-Build Resources"
        Parameters:
          - PreIndexOpenSearch
      - Label:
          default: "Generative AI Optional Integrations"
        Parameters:
          - BedrockProductPersonalization
          - DeployRoomMakeoverDemo
      - Label:
          default: "Custom Cloudfront domain name (optional)"
        Parameters:
          - CloudfrontCustomDomain
          - ACMCertificateArn          
 
    ParameterLabels:
      ResourceBucket:
        default: "retail-store-demo-bucket"
      ResourceBucketRelativePath:
        default: "Deployment Resources Staging Bucket Relative Path (optional)"
      CreateOpenSearchServiceLinkedRole:
        default: "Create OpenSearch Service Role?"
      SourceDeploymentType:
        default: "Deployment Type"
      GitHubRepo:
        default: "retail-demo-store"
      GitHubBranch:
        default: "Master"
      GitHubUser:
        default: "shibearati"
      GitHubToken:
        default: "GitHub Personal Access Token (optional)"
      PreIndexOpenSearch:
        default: "Auto-Load OpenSearch Index"
      BedrockProductPersonalization:
        default: "Enable Amazon Bedrock product personalization"
      DeployRoomMakeoverDemo:
        default: "Deploy Room Makeover Demo"
      CloudfrontCustomDomain:
        default: "Custom Cloudfront Domain"
      ACMCertificateArn:
        default: "ACM Certificate ARN"
 
Parameters:
  ResourceBucket:
    Type: String
    Description: >
      S3 bucket name where the Retail Demo Store deployment resources are staged (product images, nested CloudFormation templates, source code snapshot,
      notebooks, deployment Lambda code, etc).
 
  ResourceBucketRelativePath:
    Type: String
    Description: >
      Optional path in the Deployment Resources Staging bucket where the deployment resources are stored (e.g. path/path2/).
      Leave blank if resources are at the root of the Staging Resource Bucket. If specified, MUST end with '/'.
    Default: ''
 
  CreateOpenSearchServiceLinkedRole:
    Type: String
    Description: >
      If your account already has an IAM Role named 'AWSServiceRoleForAmazonOpenSearchService', select 'No'. Otherwise, select 'Yes' and one will be created.
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"
 
  SourceDeploymentType:
    Type: String
    Description: >
      The Retail Demo Store deployment includes a CodePipeline configuration that will build and deploy Retail Demo Store
      microservices to ECS when a change is detected in the source repository. The source repository for CodePipeline
      can be configured to use your personal GitHub repository or CodeCommit. Use GitHub if you're actively developing
      against Retail Demo Store in your own fork. CodeCommit is useful when you just want to get up and going quickly for
      a demo or evaluation or for workshop scenarios, such as Event Engine, where you want attendees to have their own
      source repositories provisioned.
    AllowedValues:
      - "GitHub"
      - "CodeCommit"
    Default: "CodeCommit"
 
  GitHubRepo:
    Type: String
    Description: Name of Retail Demo Store GitHub repository. Will almost always be 'retail-demo-store'.
    Default: retail-demo-store
 
  GitHubBranch:
    Type: String
    Description: Name of GitHub branch within the GitHub repository to link to this Retail Demo Store deployment.
    Default: master
 
  GitHubUser:
    Type: String
    Description: If you are linking and deploying from a fork of the Retail Demo Store repository, enter your GitHub username. Otherwise, use the default of 'aws-samples' to link to the upstream repository.
    Default: shibearati
 
  GitHubToken:
    Type: String
    Description: >
      If you are linking and deploying from a private fork of the Retail Demo Store repository in your GitHub account, a GitHub Personal
      Access Token is required. Otherwise, leave blank. Be sure that your token has the "repo", "repo:status", and "admin:repo_hook" permission scopes.
    NoEcho: true
    Default: ''
 
  PreIndexOpenSearch:
    Type: String
    Description: >
      Automatically index the Retail Demo Store products in OpenSearch. Otherwise, select 'No' if you would
      prefer to complete this process yourself by stepping through the Search workshop included in this deployment
      as a Jupyter notebook in SageMaker.
    AllowedValues:
      - "Yes"
      - "No"
    Default: "No"
 
  BedrockProductPersonalization:
    Type: String
    Description: Flag to enable product personalization in web-ui feature driven by Bedrock.
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'No'
 
  CloudfrontCustomDomain:
    Type: String
    Description : OPTIONAL only enter if you plan to use a custom domain named (linked to ACMCertificateArn)
    Default: ''
 
  ACMCertificateArn:
    Type: String
    Description: ACM Certificate ARN for CloudFront WebUICDN (Optional, only needed for custom domain in CloudFront)
    Default: ''
 
Mappings:
  BedrockRegionMap:
    us-east-1:
      SupportsRequiredModels: "Yes"
    us-west-2:
      SupportsRequiredModels: "Yes"
    ap-south-1:
      SupportsRequiredModels: "Yes"
    ap-southeast-2:
      SupportsRequiredModels: "Yes"
    eu-west-3:
      SupportsRequiredModels: "Yes"
 
Conditions:
  ConditionCustomDomain: !Not
    - !Equals [!Ref CloudfrontCustomDomain, ""]
 
  RegionSupportsRequiredBedrockModels: !Equals
    - !FindInMap [BedrockRegionMap, !Ref 'AWS::Region', 'SupportsRequiredModels', DefaultValue: 'No']
    - 'Yes'
 
  DeployRoomMakeoverStack: !And
    - !Equals [!Ref DeployRoomMakeoverDemo, "Yes"]
    - !Condition RegionSupportsRequiredBedrockModels
 
Resources:
  # Base Resources
  Base:
    Type: AWS::CloudFormation::Stack
    Properties:
TemplateURL: !Sub https://s3.amazonaws.com/${ResourceBucket}/${ResourceBucketRelativePath}cloudformation-templates/base/_template.yaml
      Parameters:
        ResourceBucket: !Ref ResourceBucket
        ResourceBucketRelativePath: !Ref ResourceBucketRelativePath
        SourceDeploymentType: !Ref SourceDeploymentType
        CreateOpenSearchServiceLinkedRole: !Ref CreateOpenSearchServiceLinkedRole
        CleanupBucketLambdaArn: !GetAtt CleanupBucket.Outputs.LambdaFunctionArn
        AmplitudeApiKey: !Ref AmplitudeApiKey
        ParentStackName: !Ref AWS::StackName
        GitHubUser: !Ref GitHubUser
        GitHubBranch: !Ref GitHubBranch
        GitHubToken: !Ref GitHubToken
        ACMCertificateArn: !Ref ACMCertificateArn
        ResourceBucketImages: !Ref ResourceBucketImages
        ResourceBucketImagesPrefix: !Ref ResourceBucketImagesPrefix
